###

GET http://localhost/Power%20Lab/Power-Lab/Power%20Lab/public/users/get

###

GET http://localhost/Power%20Lab/Power-Lab/Power%20Lab/public/users/get/1
Authorization: Bearer eyJ1c2VySWQiOjEsImV4cCI6MTc4OTg1MzE4NX0=.f93ba59680cde2992ee78a8197b91503ccd8a74d9adcb6973524606e4ad7daa4

###

POST http://localhost/Power%20Lab/Power-Lab/Power%20Lab/public/users/post
Content-Type: application/json

{
    "name": "Leonardo",
    "email": "teste@email.com",
    "password": "123456"
}

###
PUT http://localhost/Power%20Lab/Power-Lab/Power%20Lab/public/users/put/1
Content-Type: application/json
Authorization: Bearer eyJ1c2VySWQiOjEsImV4cCI6MTc4OTg1MzE4NX0=.f93ba59680cde2992ee78a8197b91503ccd8a74d9adcb6973524606e4ad7daa4

{
    "name": "Leonardo",
    "email": "testeee@email.com"
}


###

DELETE http://localhost/Power%20Lab/Power-Lab/Power%20Lab/public/users/delete/1
Authorization: Bearer eyJ1c2VySWQiOjEsImV4cCI6MTc4OTg1MzE4NX0=.f93ba59680cde2992ee78a8197b91503ccd8a74d9adcb6973524606e4ad7daa4

###

POST http://localhost/Power%20Lab/Power-Lab/Power%20Lab/public/users/login
Content-Type: application/json

{
    "email": "teste@email.com",
    "password": "12345"
}